### ISSUE TITLE
Cannot run setup the starter-kit

### ISSUE THREAD

**Issue by HibaH1** [DomoApps/starter-kit#67]
Hi all,
I'm trying to launch the starter-kit, but when i try "npm run setup", I have the error below:

```
> start-kit@0.0.0 setup ...\starter-kit
> node other/setup.js

...\starter-kit\other\init-repo.es6.js:123
        throw _iteratorError;
        ^

TypeError: Cannot read property 'indexOf' of undefined
    at hasChangedOriginRemote (.../starter-kit/other/init-repo.es6.js:65:9)
    at Object.<anonymous> (.../starter-kit/other/init-repo.es6.js:38:12)
    at Module._compile (module.js:570:32)
    at loader (...\starter-kit\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (...\starter-kit\node_modules\babel-registe
r\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "...\\nodejs\\node.exe" "...\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "se
tup"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! start-kit@0.0.0 setup: `node other/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the start-kit@0.0.0 setup script 'node other/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the start-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node other/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs start-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls start-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ...\starter-kit\npm-debug.log
```
Can anyone help me please?

Thanks

**Comment by HibaH1** [comment]
Hi All,

I succeded to resolve the previous problem.
For now , when I run `npm run upload`, everything is working fine, and I have my application published on domo platform; but whrn I want to create a card with the app, I have the error below displayed on the card:

`{"status":404,"statusReason":"Not Found","message":"com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: ...), S3 Extended Request ID: ...","toe":"..."}`

Any ideas please?

Thanks

**Comment by walexnelson** [comment]
@HibaH1 this new error isn't related to the starter kit but rather the app platform. I recommend you send this error to Domo Support so they can look into for you.

**Comment by josevelez** [comment]
hi @HibaH1 How did you solve the first problem.? 
Thanks
